### ISSUE TITLE
Support syntax highlighting

### ISSUE THREAD

**Issue by fioncat** [fioncat/otree#15]
Implement syntax highlighting in data block.

Allow user to define highlighting colors.

**Comment by ccoVeille** [comment]
For reference and curious people like me

https://github.com/rust-bakery/nom

**Comment by fioncat** [comment]
> For reference and curious people like me
> 
> https://github.com/rust-bakery/nom

I found that we don't need to use `nom` anymore, since `serde_*` crates has already done that.

You can review my PR if you are interested 🙃

**Comment by ccoVeille** [comment]
Maybe you could update the issue description then
